name: Python CI with pytest

on:
  push:
    branches: all_Automation_Actions
  pull_request:
    branches: all_Automation_Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        cd /home/runner/work/all-learner-ai-app/all-learner-ai-app/allAutomation
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyaudio

    - name: Run tests
      run: |
        cd /home/runner/work/all-learner-ai-app/all-learner-ai-app/allAutomation
        pytest tests/microphoneSimulationTest.py








